package loginandsignup;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author DELL
 */
public class SignUp extends javax.swing.JFrame {

    private JPanel panel1;
    private JRadioButton level0RadioButton;
    private JRadioButton level1RadioButton;
    private JRadioButton level2RadioButton;
    private JRadioButton level3RadioButton;
    private JRadioButton level4RadioButton;
    private ButtonGroup levelButtonGroup; // To group radio buttons
    private JTextArea academicLevelTextArea;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel(); // Image label
        jLabel7 = new javax.swing.JLabel(); // Welcome text
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        levelButtonGroup = new ButtonGroup();
        level0RadioButton = new JRadioButton();
        level1RadioButton = new JRadioButton();
        level2RadioButton = new JRadioButton();
        level3RadioButton = new JRadioButton();
        level4RadioButton = new JRadioButton();
        jLabel10 = new javax.swing.JLabel(); // New label for "Academic level"

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 0, 9));
        jPanel2.setLayout(null);

        // Set Welcome text
        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", Font.PLAIN, 24));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Welcome to FEHU CPC");
        jLabel7.setBounds(44, 33, 308, 30);
        jPanel2.add(jLabel7);

        // Add and scale the image
        try {
            java.net.URL imgURL = getClass().getResource("/loginandsignup/fehucpc.jpg");
            if (imgURL != null) {
                java.awt.image.BufferedImage originalImg = javax.imageio.ImageIO.read(imgURL);
                if (originalImg != null) {
                    java.awt.image.BufferedImage scaledImg = new java.awt.image.BufferedImage(200, 200, java.awt.image.BufferedImage.TYPE_INT_ARGB);
                    java.awt.Graphics2D g2d = scaledImg.createGraphics();
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g2d.drawImage(originalImg, 0, 0, 200, 200, null);
                    g2d.dispose();
                    jLabel1.setIcon(new javax.swing.ImageIcon(scaledImg));
                    System.out.println("Image scaled to 200x200 and set in JLabel.");
                } else {
                    System.out.println("Error: Image could not be read.");
                    jLabel1.setText("Image Invalid");
                    jLabel1.setForeground(Color.WHITE);
                }
            } else {
                System.out.println("Warning: Image /loginandsignup/fehucpc.jpg not found.");
                jLabel1.setText("Logo Missing");
                jLabel1.setForeground(Color.WHITE);
            }
        } catch (Exception e) {
            System.out.println("Error loading image: " + e.getMessage());
            jLabel1.setText("Image Error");
            jLabel1.setForeground(Color.WHITE);
        }
        jLabel1.setBounds(100, 70, 200, 200); // Position below welcome text
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 1));
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 500);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36));
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Sign Up");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 30, 140, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Full name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 90, 70, 20);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(430, 110, 310, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("Phone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 150, 50, 20);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(430, 170, 310, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Gmail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 210, 37, 16);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(430, 230, 310, 30);

        // Initialize and add radio buttons with "Academic level" label above
        levelButtonGroup = new ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel10.setText("Academic level");
        jLabel10.setBounds(430, 270, 100, 20);
        jPanel1.add(jLabel10);

        level0RadioButton.setText("level 0");
        level0RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
        level0RadioButton.setForeground(new java.awt.Color(102, 0, 0));
        levelButtonGroup.add(level0RadioButton);
        jPanel1.add(level0RadioButton);
        level0RadioButton.setBounds(430, 290, 100, 20);

        level1RadioButton.setText("level 1");
        level1RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
        level1RadioButton.setForeground(new java.awt.Color(102, 0, 0));
        levelButtonGroup.add(level1RadioButton);
        jPanel1.add(level1RadioButton);
        level1RadioButton.setBounds(530, 290, 100, 20);

        level2RadioButton.setText("level 2");
        level2RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
        level2RadioButton.setForeground(new java.awt.Color(102, 0, 0));
        levelButtonGroup.add(level2RadioButton);
        jPanel1.add(level2RadioButton);
        level2RadioButton.setBounds(630, 290, 100, 20);

        level3RadioButton.setText("level 3");
        level3RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
        level3RadioButton.setForeground(new java.awt.Color(102, 0, 0));
        levelButtonGroup.add(level3RadioButton);
        jPanel1.add(level3RadioButton);
        level3RadioButton.setBounds(480, 310, 100, 20);

        level4RadioButton.setText("level 4");
        level4RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
        level4RadioButton.setForeground(new java.awt.Color(102, 0, 0));
        levelButtonGroup.add(level4RadioButton);
        jPanel1.add(level4RadioButton);
        level4RadioButton.setBounds(580, 310, 100, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 340, 70, 20);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(430, 360, 310, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel9.setText("Codeforce account");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 400, 120, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(430, 420, 310, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5; // Still in variables declaration but not used
    private javax.swing.JTextField jTextField6;

    private javax.swing.JLabel jLabel10; // New label for "Academic level"
    // End of variables declaration//GEN-END:variables
}